name: divbrowse_dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9,<3.13
  - click
  - numpy>=1.21.1,<2
  - pandas
  - flask
  - scikit-learn
  - scikit-allel
  - seaborn
  - bioblend>=0.16.0
  - pyyaml
  - zarr>=2.8.3,<3
  - pytables
  - waitress
  - simplejson
  - orjson
  - umap-learn
  - numcodecs
  - poetry-core